#pragma once
#include "ClientLog.h"
#include <climits>

// Read-only, bounded observations. No packet rewriting or damage calculation.
namespace EvanAttackDiagnostics {
struct Target { void* mob; int oid; };
struct Render { DWORD tick; void* mob; int damage; int line; int critical; bool forwarded; };
struct State {
    unsigned casts = 0, records = 0, cursor = 0;
    struct SkillBudget { int skill = 0; unsigned casts = 0; } skills[32]{};
    int skill = 0;
    DWORD started = 0;
    bool active = false;
    Target targets[15]{};
    unsigned count = 0;
    Render recent[256]{};
};
inline State& Current() { static thread_local State state; return state; }
inline bool Enabled() {
    static const bool enabled = [] { char value[8]{};
        GetEnvironmentVariableA("BEIDOU_EVAN_ATTACK_LOG", value, sizeof(value));
        return value[0] != '0'; }();
    return enabled;
}
inline int I32(const unsigned char* p) {
    return static_cast<int>(static_cast<unsigned>(p[0]) | (static_cast<unsigned>(p[1]) << 8)
        | (static_cast<unsigned>(p[2]) << 16) | (static_cast<unsigned>(p[3]) << 24));
}
struct BeaconState {
    unsigned records=0, epoch=1;
    int target=0;
    struct Seen { void* mob=nullptr; int oid=0; unsigned epoch=0; } seen[32]{};
};
inline BeaconState& Beacon() { static thread_local BeaconState state; return state; }
inline void TrackBeacon(void* mob, int oid) {
    if (!mob) return;
    for (auto& entry:Beacon().seen) if (entry.mob==mob || !entry.mob) {
        entry.mob=mob; entry.oid=oid; return;
    }
}
inline void BeaconRetention(void* mob, int skill, int retained) {
    if (!Enabled() || skill!=22151002) return;
    auto& s=Beacon();
    for(auto& entry:s.seen) if(entry.mob==mob && entry.epoch!=s.epoch && s.records<128) {
        entry.epoch=s.epoch; ++s.records;
        ClientLog::Append(ClientLog::Component::Trace,
            "event=evan_beacon_marker oid=%d receivedTarget=%d retainedByNative=%d epoch=%u",
            entry.oid,s.target,retained,s.epoch);
        return;
    }
}
inline void BeaconPacket(const unsigned char* data, unsigned long size, bool incoming) {
    if (!Enabled() || !incoming || !data || size<22 || data[5]!=0 ||
        (data[4]!=0x20 && data[4]!=0x21) || !(data[12]&0x80)) return;
    auto& s=Beacon();
    if (s.records>=128) return;
    // Only decode the exact single-beacon layout generated by giveBuff. Mixed
    // masks/truncated packets are recorded but never read at assumed offsets.
    bool single=true;
    for(unsigned i=6;i<22;++i) if(data[i]!=(i==12?0x80:0)) single=false;
    ++s.records; ++s.epoch;
    const int previous=s.target;
    const bool decoded=single && data[4]==0x20 && size==44;
    if(data[4]==0x21) s.target=0;
    else if(decoded) s.target=I32(data+37);
    ClientLog::Append(ClientLog::Component::Trace,
        "event=evan_beacon_packet opcode=%u size=%lu decoded=%d previous=%d target=%d reason=%d duration=%d epoch=%u",
        data[4],size,decoded,previous,s.target,decoded?I32(data+24):0,decoded?I32(data+28):0,s.epoch);
}
inline void* FindMob(int oid) {
#ifdef EVAN_ATTACK_DIAGNOSTICS_TEST
    return reinterpret_cast<void*>(static_cast<uintptr_t>(oid));
#else
    void* pool = *reinterpret_cast<void**>(0x00BEBFA4);
    using Find = void* (__thiscall*)(void*, int);
    return pool ? reinterpret_cast<Find>(0x00441AE8)(pool, oid) : nullptr;
#endif
}
inline bool Budget() {
    State& s = Current();
    if (s.records >= 8192) return false;
    if (++s.records == 8192) {
        ClientLog::Append(ClientLog::Component::Trace, "event=evan_attack_limit maxRecords=8192");
        return false;
    }
    return true;
}
inline void LogRender(const Render& r, int oid, const char* phase) {
    if (Budget()) ClientLog::Append(ClientLog::Component::Trace,
        "event=evan_attack_render cast=%u skill=%d phase=%s tick=%lu oid=%d damage=%d line=%d criticalArg=%d forwarded=%d correlation=target_time_candidate",
        Current().casts, Current().skill, phase, r.tick, oid, r.damage, r.line, r.critical, r.forwarded);
}
inline void RemoteAction(int skill, int action, int accepted) {
    State& s = Current();
    if (Enabled() && s.active && s.skill == skill && Budget())
        ClientLog::Append(ClientLog::Component::Trace,
            "event=evan_remote_action cast=%u skill=%d action=%d accepted=%d",
            s.casts, skill, action, accepted);
}
inline void RemoteGeometry(int skill, int index, int origin, int left, int right, int top, int bottom, int facing) {
    State& s = Current();
    if (Enabled() && s.active && s.skill == skill && Budget())
        ClientLog::Append(ClientLog::Component::Trace,
            "event=evan_remote_geometry cast=%u skill=%d index=%d origin=%d rect=%d,%d,%d,%d facing=%d projectileWouldBreak=%d",
            s.casts, skill, index, origin, left, top, right, bottom, facing,
            left >= right || top >= bottom || (facing ? origin <= right : origin >= left));
}
inline void RenderCall(void* mob, int damage, int line, int critical, bool forwarded) {
    if (!Enabled()) return;
    State& s = Current();
    if (s.records >= 8192) return;
    Render r{GetTickCount(), mob, damage, line, critical, forwarded};
    s.recent[s.cursor++ % 256] = r;
    if (!s.active || r.tick - s.started > 5000) return;
    for (unsigned i = 0; i < s.count; ++i) if (mob && s.targets[i].mob == mob) {
        LogRender(r, s.targets[i].oid, "after_packet"); break;
    }
}
inline void Packet(const unsigned char* data, unsigned long size, bool incoming) {
    if (!Enabled()) return;
    // Incoming buffers include the native four-byte transport prefix.
    const unsigned base = incoming ? 4 : 0;
    const unsigned skillOffset = incoming ? 13 : 4;
    if (!data || size < skillOffset + 4 || data[base] != (incoming ? 0xBC : 0x2E)
        || data[base + 1] != 0 || (incoming && data[12] == 0)
        || I32(data + skillOffset) / 1000000 != 22) return;
    State& s = Current();
    if (s.records >= 8192) return;
    // Reserve samples for every skill instead of consuming the entire session
    // budget on the first attack. Stop attribution when an unsampled cast starts.
    s.active = false;
    const int skill = I32(data + skillOffset);
    State::SkillBudget* budget = nullptr;
    for (auto& entry : s.skills) if (entry.skill == skill || entry.skill == 0) {
        budget = &entry; break;
    }
    if (!budget || budget->casts >= 8) return;
    budget->skill = skill; ++budget->casts;
    ++s.casts;
    s.skill = I32(data + skillOffset);
    s.started = GetTickCount(); s.active = true; s.count = 0;
    const unsigned packed = data[incoming ? 10 : 3];
    const unsigned targets = packed >> 4, lines = packed & 15;
    const bool charged = s.skill == 22121000 || s.skill == 22151001;
    const unsigned header = incoming ? 26 : (charged ? 29 : 25);
    const unsigned stride = (incoming ? 5 : 22) + lines * 4;
    const unsigned expected = header + targets * stride + (incoming && charged ? 4 : 0);
    if (Budget()) ClientLog::Append(ClientLog::Component::Trace,
        "event=evan_attack_packet cast=%u skill=%d side=%s tick=%lu actor=%d targets=%u lines=%u size=%lu expected=%u valid=%d",
        s.casts, s.skill, incoming ? "receive" : "send", s.started, incoming ? I32(data+6) : 0,
        targets, lines, size, expected, size >= expected);
    if (size < expected) return;
    for (unsigned i = 0; i < targets; ++i) {
        const unsigned char* entry = data + header + i * stride;
        const int oid = I32(entry);
        void* mob = FindMob(oid);
        s.targets[s.count++] = {mob, oid};
        if(s.skill==22151002) { ++Beacon().epoch; TrackBeacon(mob,oid); }
        if (!incoming && Budget()) ClientLog::Append(ClientLog::Component::Trace,
            "event=evan_attack_footer cast=%u skill=%d index=%u oid=%d footer=0x%08X",
            s.casts, s.skill, i, oid, static_cast<unsigned>(I32(entry + 18 + lines * 4)));
        for (unsigned line = 0; line < lines; ++line) {
            const int raw = I32(entry + (incoming ? 5 : 18) + line * 4);
            if (Budget()) ClientLog::Append(ClientLog::Component::Trace,
                "event=evan_attack_target cast=%u side=%s index=%u oid=%d mobPresent=%d line=%u raw=%d signBit=%d magnitudeBits=%d",
                s.casts, incoming ? "receive" : "send", i, oid, mob != nullptr, line, raw, raw < 0, raw & INT_MAX);
        }
        if (!incoming && mob) for (unsigned j = 0; j < 256; ++j) {
            const Render& r = s.recent[j];
            if (r.mob == mob && s.started - r.tick <= 3000) LogRender(r, oid, "before_send");
        }
    }
}
inline void Observe(const unsigned char* data, unsigned long size, bool incoming) {
    const DWORD saved = GetLastError();
    __try { BeaconPacket(data,size,incoming); Packet(data, size, incoming); }
    __except (EXCEPTION_EXECUTE_HANDLER) {
        if (Budget()) ClientLog::Append(ClientLog::Component::Trace,
            "event=evan_attack_observer_exception code=0x%08lX", GetExceptionCode());
    }
    SetLastError(saved);
}
}
